---
- name: Configure credentials
  become: yes
  template:
    src: inventory.j2
    dest: "{{ tmp_folder }}/ansible-tower-setup-{{ tower_version }}/inventory"

- name: Execute installation
  become: yes
  shell: "./setup.sh"
  args:
    chdir: "{{ tmp_folder }}/ansible-tower-setup-{{ tower_version }}"
    creates: "/etc/tower/successfully_installed"
    executable: /bin/bash

- name: Create successfully_installed in tower folder
  become: yes
  file:
    state: touch
    path: /etc/tower/successfully_installed

- name: Upgrade tower
  become: yes
  shell: "./setup.sh"
  args:
    chdir: "{{ tmp_folder }}/ansible-tower-setup-{{ tower_version }}"
    executable: /bin/bash
  environment:
    PATH: "{{ ansible_env.PATH}}:/sbin:/usr/sbin"
  when: perform_upgrade
