---
- name: Install custom ssl certificate
  become: yes
  copy:
    src: "vars/vault/certificates/{{ item }}"
    dest: "/etc/tower/{{ item }}"
    group: awx
  with_items:
    - tower.cert
    - tower.key
  notify: restart_tower