---
# handlers file for ansible-tower
- name: restart_tower
  become: true
  shell: ansible-tower-service restart
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ ansible_env.PATH}}:/sbin:/usr/sbin"